// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//

var fibonacci = function(upper_bound) {
  var sequence = [1, 2];
  for(i = 2; i < upper_bound; i++) {
    var n = (sequence[sequence.length - 1] + sequence[sequence.length - 2]);
    sequence.push(n);
  }  
  return sequence;
}

var sumAll = function(list) {
  var sum = list.reduce(function(prev, curr) { 
    return prev + curr; 
  });
  return sum;
}

var sumEvens = function(list) {
  var total = 0;
  for(i = 0; i < list.length; i++) {
    if(list[i] % 2 === 0){
     total += list[i]; 
    }
  }
  return total;
}


console.log("Sum of all fibonacci numbers up to 30: " + sumAll( fibonacci(30)));
console.log("Sum of all even fibonacci numbers up to 30: " +  sumEvens(fibonacci(30)));
